### ISSUE TITLE
Accessibility in print mode

### ISSUE THREAD

**Issue by sabarigr** [a11yproject/a11yproject.com#429]
Hi,
A11Y Project is a good initiative to help developers like me to create accessible websites and applications. During my recent visit to my website I noticed that the urls in your website weren't made printer friendly, so i created this fiddle solving that.
Please visit https://jsfiddle.net/sabarigr/cqsp6n3f/

Thank you!
Kudos again to your initiative :+1:

**Comment by jpdevries** [comment]
This is really clever! Speaking of print stylesheets, I'm curious if there is a general consensus on if using `!important` declarations for print style sheets is reasonable.

Example:
```css
@media print {
  * {
    background: white !important;
    color: black !important;
    border-color: grey !important;
  }
  .ads {
    display: none !important;
  }
}
```
