### ISSUE TITLE
Unannounced list semantics in VoiceOver

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#685]
Per the [VoiceOver and list-style-type: none](https://unfetteredthoughts.net/2017/09/26/voiceover-and-list-style-type-none/) bug, the listing of content on the home page (and likely other areas of The A11y Project site) do not convey list semantics to VoiceOver due to their styling.

Modifying the site's CSS to account for this bug will allow the intended semantics to be conveyed by VoiceOver.

High level example of fix:
```css
.list li {
  list-style-type: none; /* remove bullets */
}
 
.list li:before {
  content: "\200B"; /* add zero-width space */
}
```
